mybatis:
  type-aliases-package: com.moxuan.Proj.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
